language: go
script:
- go fmt ./
notifications:
  slack:
    secure: vIue78edhVHZJAsITRjREhJeYtp/WatWzWajCjJ2BivCszEwN+EAGVChbItLlRNjSZ+v+AvRcy7JXZ7qzlNnoRSZ66cl92zlfCq25rL8w70v7dBiVVzUDqhgMvQerHyLpeDe1plUz9d7NjLmnTlQsTBWjAjHMvYa4gCNDCFTeN6iawwBXq1zySPvkKSJ1vw7ezhtJkxLL/n193XtewZ1kkJgYE1IbKX7BgW0L1GFvMvn5ugJ+8CyEj/93ju+sOXRzEpPbtjlakn4x4IBiOMuXyLKdqi3ukbCGpN3cYIY/elrTg83KVFpTs4qz9bOk+KP+clkvDlccJ2Gz8UZ7vnBZzcyNxTTTxfm7NEhRUI7MyGlp+agR9hOg0/BNUjREFK7jjTBz4Y17UhTe/YhmJLe+3PZej907lL9HfL58ol4SZwS8b4etRiWst6X51BmTeMms+4dtSJCLJWVXm+UZCZvSiw+rX8TsQ19tAx0tKr2PHY2O5oy/ag1rQTKAgGs/gyJxsLg2+o1mQ4uI+rPkSSx5aQS96/RgPjWj5pFK7ZXWetjZwTjJkwzWGOlQUSVunvUnctervGWInwZOHYdYi0i1Bt43+S8+5lgVFAtHwsZQRH5GW5L2sXk5NjbRFH5oVLieV5O8KoPzSwnf4QhJqFBo0zS1XBrAqHZ3QH3hqMvbAw=
