[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.10"

[[constraint]]
  branch = "master"
  name = "github.com/ignw/cisco-aci-go-sdk"

[prune]
  go-tests = true
  unused-packages = true
